Changed the tab indentation for double spaces

diff --git a/release-new-version b/release-new-version
--- a/release-new-version
+++ b/release-new-version
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 if [[ ! -x $(which git) ]]; then
-	echo -e "\e[31m!  ERROR: Can't find the Git executable\e[00m"
-	exit 1
+  echo -e "\e[31m!  ERROR: Can't find the Git executable\e[00m"
+  exit 1
 fi
 
 if [[ ! -x $(which go) ]]; then
-	echo -e "\e[31m!  ERROR: Can't find the Go executable\e[00m"
-	exit 1
+  echo -e "\e[31m!  ERROR: Can't find the Go executable\e[00m"
+  exit 1
 fi
 
 if [ ! -z "`git status -s`" ]; then
