Added a check to see if the Git executable is available

diff --git a/release-new-version b/release-new-version
--- a/release-new-version
+++ b/release-new-version
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [[ ! -x $(which git) ]]; then
+	echo -e "\e[31m!  ERROR: Can't find the Git executable\e[00m"
+	exit 1
+fi
+
 if [ ! -z "`git status -s`" ]; then
   echo -e "\e[31m!  ERROR: please ensure you have added and committed all your changes first\e[00m"
   exit 1
